/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include "absyn.h"
#include "misc.h"
#include <stdio.h>
#include <stdlib.h>

/********************   Prog    ********************/
Program
make_Prog(ListTopDef p1)
{
    Program tmp = (Program)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Prog;
    tmp->u.prog_.listtopdef_ = p1;
    return tmp;
} /********************   FnDef    ********************/
TopDef
make_FnDef(Type p1, Ident p2, ListArg p3, Block p4)
{
    TopDef tmp = (TopDef)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_FnDef;
    tmp->u.fndef_.type_ = p1;
    tmp->u.fndef_.ident_ = p2;
    tmp->u.fndef_.listarg_ = p3;
    tmp->u.fndef_.block_ = p4;
    return tmp;
}
/********************   ClDef    ********************/
TopDef
make_ClDef(Ident p1, ClProps p2, ListClBody p3)
{
    TopDef tmp = (TopDef)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ClDef;
    tmp->u.cldef_.ident_ = p1;
    tmp->u.cldef_.clprops_ = p2;
    tmp->u.cldef_.listclbody_ = p3;
    return tmp;
} /********************   ListTopDef    ********************/
ListTopDef
make_ListTopDef(TopDef p1, ListTopDef p2)
{
    ListTopDef tmp = (ListTopDef)alloc_ast_node(sizeof(*tmp));
    tmp->topdef_ = p1;
    tmp->listtopdef_ = p2;
    return tmp;
} /********************   Ar    ********************/
Arg
make_Ar(Type p1, Ident p2)
{
    Arg tmp = (Arg)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Ar;
    tmp->u.ar_.type_ = p1;
    tmp->u.ar_.ident_ = p2;
    return tmp;
} /********************   ListArg    ********************/
ListArg
make_ListArg(Arg p1, ListArg p2)
{
    ListArg tmp = (ListArg)alloc_ast_node(sizeof(*tmp));
    tmp->arg_ = p1;
    tmp->listarg_ = p2;
    return tmp;
} /********************   Blk    ********************/
Block
make_Blk(ListStmt p1)
{
    Block tmp = (Block)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Blk;
    tmp->u.blk_.liststmt_ = p1;
    return tmp;
} /********************   ListStmt    ********************/
ListStmt
make_ListStmt(Stmt p1, ListStmt p2)
{
    ListStmt tmp = (ListStmt)alloc_ast_node(sizeof(*tmp));
    tmp->stmt_ = p1;
    tmp->liststmt_ = p2;
    return tmp;
} /********************   Empty    ********************/
Stmt
make_Empty()
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Empty;
    return tmp;
}
/********************   BStmt    ********************/
Stmt
make_BStmt(Block p1)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_BStmt;
    tmp->u.bstmt_.block_ = p1;
    return tmp;
}
/********************   Decl    ********************/
Stmt
make_Decl(Type p1, ListItem p2)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Decl;
    tmp->u.decl_.type_ = p1;
    tmp->u.decl_.listitem_ = p2;
    return tmp;
}
/********************   Ass    ********************/
Stmt
make_Ass(Expr p1, Expr p2)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Ass;
    tmp->u.ass_.expr_1 = p1;
    tmp->u.ass_.expr_2 = p2;
    return tmp;
}
/********************   Incr    ********************/
Stmt
make_Incr(Expr p1)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Incr;
    tmp->u.incr_.expr_ = p1;
    return tmp;
}
/********************   Decr    ********************/
Stmt
make_Decr(Expr p1)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Decr;
    tmp->u.decr_.expr_ = p1;
    return tmp;
}
/********************   Ret    ********************/
Stmt
make_Ret(Expr p1)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Ret;
    tmp->u.ret_.expr_ = p1;
    return tmp;
}
/********************   VRet    ********************/
Stmt
make_VRet()
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_VRet;
    return tmp;
}
/********************   Cond    ********************/
Stmt
make_Cond(Expr p1, Stmt p2)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Cond;
    tmp->u.cond_.expr_ = p1;
    tmp->u.cond_.stmt_ = p2;
    return tmp;
}
/********************   CondElse    ********************/
Stmt
make_CondElse(Expr p1, Stmt p2, Stmt p3)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_CondElse;
    tmp->u.condelse_.expr_ = p1;
    tmp->u.condelse_.stmt_1 = p2;
    tmp->u.condelse_.stmt_2 = p3;
    return tmp;
}
/********************   While    ********************/
Stmt
make_While(Expr p1, Stmt p2)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_While;
    tmp->u.while_.expr_ = p1;
    tmp->u.while_.stmt_ = p2;
    return tmp;
}
/********************   For    ********************/
Stmt
make_For(Ident p1, Ident p2, Expr p3, Stmt p4)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_For;
    tmp->u.for_.ident_1 = p1;
    tmp->u.for_.ident_2 = p2;
    tmp->u.for_.expr_ = p3;
    tmp->u.for_.stmt_ = p4;
    return tmp;
}
/********************   SExp    ********************/
Stmt
make_SExp(Expr p1)
{
    Stmt tmp = (Stmt)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_SExp;
    tmp->u.sexp_.expr_ = p1;
    return tmp;
} /********************   NoInit    ********************/
Item
make_NoInit(Ident p1)
{
    Item tmp = (Item)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_NoInit;
    tmp->u.noinit_.ident_ = p1;
    return tmp;
}
/********************   Init    ********************/
Item
make_Init(Ident p1, Expr p2)
{
    Item tmp = (Item)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Init;
    tmp->u.init_.ident_ = p1;
    tmp->u.init_.expr_ = p2;
    return tmp;
} /********************   ListItem    ********************/
ListItem
make_ListItem(Item p1, ListItem p2)
{
    ListItem tmp = (ListItem)alloc_ast_node(sizeof(*tmp));
    tmp->item_ = p1;
    tmp->listitem_ = p2;
    return tmp;
} /********************   TCls    ********************/
Type
make_TCls(Ident p1)
{
    Type tmp = (Type)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_TCls;
    tmp->u.tcls_.ident_ = p1;
    return tmp;
}
/********************   TArr    ********************/
Type
make_TArr(Ident p1)
{
    Type tmp = (Type)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_TArr;
    tmp->u.tarr_.ident_ = p1;
    return tmp;
} /********************   EVar    ********************/
Expr
make_EVar(Ident p1)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EVar;
    tmp->u.evar_.ident_ = p1;
    return tmp;
}
/********************   EApp    ********************/
Expr
make_EApp(Ident p1, ListExpr p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EApp;
    tmp->u.eapp_.ident_ = p1;
    tmp->u.eapp_.listexpr_ = p2;
    return tmp;
}
/********************   EClMem    ********************/
Expr
make_EClMem(Expr p1, Ident p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EClMem;
    tmp->u.eclmem_.expr_ = p1;
    tmp->u.eclmem_.ident_ = p2;
    return tmp;
}
/********************   EClApp    ********************/
Expr
make_EClApp(Expr p1, Ident p2, ListExpr p3)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EClApp;
    tmp->u.eclapp_.expr_ = p1;
    tmp->u.eclapp_.ident_ = p2;
    tmp->u.eclapp_.listexpr_ = p3;
    return tmp;
}
/********************   EArrApp    ********************/
Expr
make_EArrApp(Expr p1, Expr p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EArrApp;
    tmp->u.earrapp_.expr_1 = p1;
    tmp->u.earrapp_.expr_2 = p2;
    return tmp;
}
/********************   ENew    ********************/
Expr
make_ENew(Ident p1)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ENew;
    tmp->u.enew_.ident_ = p1;
    return tmp;
}
/********************   ENewArr    ********************/
Expr
make_ENewArr(Ident p1, Expr p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ENewArr;
    tmp->u.enewarr_.ident_ = p1;
    tmp->u.enewarr_.expr_ = p2;
    return tmp;
}
/********************   ELitInt    ********************/
Expr
make_ELitInt(Integer p1)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ELitInt;
    tmp->u.elitint_.integer_ = p1;
    return tmp;
}
/********************   ELitStr    ********************/
Expr
make_ELitStr(String p1)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ELitStr;
    tmp->u.elitstr_.string_ = p1;
    return tmp;
}
/********************   ELitTrue    ********************/
Expr
make_ELitTrue()
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ELitTrue;
    return tmp;
}
/********************   ELitFalse    ********************/
Expr
make_ELitFalse()
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ELitFalse;
    return tmp;
}
/********************   ENull    ********************/
Expr
make_ENull()
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ENull;
    return tmp;
}
/********************   Neg    ********************/
Expr
make_Neg(Expr p1)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Neg;
    tmp->u.neg_.expr_ = p1;
    return tmp;
}
/********************   Not    ********************/
Expr
make_Not(Expr p1)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Not;
    tmp->u.not_.expr_ = p1;
    return tmp;
}
/********************   ECast    ********************/
Expr
make_ECast(Ident p1, Expr p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ECast;
    tmp->u.ecast_.ident_ = p1;
    tmp->u.ecast_.expr_ = p2;
    return tmp;
}
/********************   EMul    ********************/
Expr
make_EMul(Expr p1, MulOp p2, Expr p3)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EMul;
    tmp->u.emul_.expr_1 = p1;
    tmp->u.emul_.mulop_ = p2;
    tmp->u.emul_.expr_2 = p3;
    return tmp;
}
/********************   EAdd    ********************/
Expr
make_EAdd(Expr p1, AddOp p2, Expr p3)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EAdd;
    tmp->u.eadd_.expr_1 = p1;
    tmp->u.eadd_.addop_ = p2;
    tmp->u.eadd_.expr_2 = p3;
    return tmp;
}
/********************   ERel    ********************/
Expr
make_ERel(Expr p1, RelOp p2, Expr p3)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_ERel;
    tmp->u.erel_.expr_1 = p1;
    tmp->u.erel_.relop_ = p2;
    tmp->u.erel_.expr_2 = p3;
    return tmp;
}
/********************   EEq    ********************/
Expr
make_EEq(Expr p1, EqOp p2, Expr p3)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EEq;
    tmp->u.eeq_.expr_1 = p1;
    tmp->u.eeq_.eqop_ = p2;
    tmp->u.eeq_.expr_2 = p3;
    return tmp;
}
/********************   EAnd    ********************/
Expr
make_EAnd(Expr p1, Expr p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EAnd;
    tmp->u.eand_.expr_1 = p1;
    tmp->u.eand_.expr_2 = p2;
    return tmp;
}
/********************   EOr    ********************/
Expr
make_EOr(Expr p1, Expr p2)
{
    Expr tmp = (Expr)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EOr;
    tmp->u.eor_.expr_1 = p1;
    tmp->u.eor_.expr_2 = p2;
    return tmp;
} /********************   ListExpr    ********************/
ListExpr
make_ListExpr(Expr p1, ListExpr p2)
{
    ListExpr tmp = (ListExpr)alloc_ast_node(sizeof(*tmp));
    tmp->expr_ = p1;
    tmp->listexpr_ = p2;
    return tmp;
} /********************   CBVar    ********************/
ClBody
make_CBVar(Type p1, Ident p2)
{
    ClBody tmp = (ClBody)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_CBVar;
    tmp->u.cbvar_.type_ = p1;
    tmp->u.cbvar_.ident_ = p2;
    return tmp;
}
/********************   CBFnDef    ********************/
ClBody
make_CBFnDef(Type p1, Ident p2, ListArg p3, Block p4)
{
    ClBody tmp = (ClBody)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_CBFnDef;
    tmp->u.cbfndef_.type_ = p1;
    tmp->u.cbfndef_.ident_ = p2;
    tmp->u.cbfndef_.listarg_ = p3;
    tmp->u.cbfndef_.block_ = p4;
    return tmp;
} /********************   ListClBody    ********************/
ListClBody
make_ListClBody(ClBody p1, ListClBody p2)
{
    ListClBody tmp = (ListClBody)alloc_ast_node(sizeof(*tmp));
    tmp->clbody_ = p1;
    tmp->listclbody_ = p2;
    return tmp;
} /********************   CNone    ********************/
ClProps
make_CNone()
{
    ClProps tmp = (ClProps)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_CNone;
    return tmp;
}
/********************   CExtends    ********************/
ClProps
make_CExtends(Ident p1)
{
    ClProps tmp = (ClProps)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_CExtends;
    tmp->u.cextends_.ident_ = p1;
    return tmp;
} /********************   Plus    ********************/
AddOp
make_Plus()
{
    AddOp tmp = (AddOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Plus;
    return tmp;
}
/********************   Minus    ********************/
AddOp
make_Minus()
{
    AddOp tmp = (AddOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Minus;
    return tmp;
} /********************   Times    ********************/
MulOp
make_Times()
{
    MulOp tmp = (MulOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Times;
    return tmp;
}
/********************   Div    ********************/
MulOp
make_Div()
{
    MulOp tmp = (MulOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Div;
    return tmp;
}
/********************   Mod    ********************/
MulOp
make_Mod()
{
    MulOp tmp = (MulOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_Mod;
    return tmp;
} /********************   LTH    ********************/
RelOp
make_LTH()
{
    RelOp tmp = (RelOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_LTH;
    return tmp;
}
/********************   LE    ********************/
RelOp
make_LE()
{
    RelOp tmp = (RelOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_LE;
    return tmp;
}
/********************   GTH    ********************/
RelOp
make_GTH()
{
    RelOp tmp = (RelOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_GTH;
    return tmp;
}
/********************   GE    ********************/
RelOp
make_GE()
{
    RelOp tmp = (RelOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_GE;
    return tmp;
} /********************   NE    ********************/
EqOp
make_NE()
{
    EqOp tmp = (EqOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_NE;
    return tmp;
}
/********************   EQU    ********************/
EqOp
make_EQU()
{
    EqOp tmp = (EqOp)alloc_ast_node(sizeof(*tmp));
    tmp->kind = is_EQU;
    return tmp;
}
